
networks:
  primary:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres1:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - primary
  
  keycloak:
    container_name: keycloak
    image: ghcr.io/wundergraph/cosmo/keycloak:latest
    environment:
      KEYCLOAK_EXTRA_ARGS: '--import-realm --optimized'
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: 'true'
      KEYCLOAK_ENABLE_STATISTICS: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: changeme
      KEYCLOAK_DATABASE_USER: postgres
    ports:
      - '8080:8080'
    volumes:
      - ./docker/keycloak/realm.json:/opt/bitnami/keycloak/data/import/realm.json:ro
  #  restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - primary

    
volumes:
  postgres1:
  